### ISSUE TITLE
Setting Time

### ISSUE THREAD

**Issue by edoxxx** [techn0man1ac/PerpetualLEDWristwatch#2]
hello, very interesting project but would it be possible to develop the code to reset the hour and minutes by taking advantage of the button? because putting back the time would mean having a computer.

let me know.

**Comment by techn0man1ac** [comment]
Hi @edoxxx yes, it's [done](https://github.com/techn0man1ac/PerpetualLEDWristwatch/commit/85db25f01018a77f09de6c6412757746059755f4).

Thank you for your request, now, in new firmware I make reset the clock press the button for more than 10 seconds.

You can test and provide feedback here.

**Comment by edoxxx** [comment]
Hello, this is a good solution, I didn't think about it. 
I was trying to structure the code so I could fix the time at any time of the day but I should use too many variables that weigh down the code too much and make it slower and harder to load into the microprocessor's poor memory. 

Maybe I could look for a micro that's compatible with more memory. 

However, I am designing a case to be 3D printed, so as to add value to the project. 

thank you so much for your answer. see you soon!!! :)

**Comment by techn0man1ac** [comment]
@edoxxx Yes, you can take a more advanced model - ATtiny85 where there is 8 times more flash memory. However, I plan to add  for ATtiny13 a time task (if you hold the button for more than 10 seconds, then the time will change every 1 second of holding the button up to 5 minutes) and so on until you release the button.

Case for watch it's would be great, if you need some dimensions - write, I will measure everything.

**Comment by edoxxx** [comment]
Wow if you could write this code, it would be great. 

I was trying to create a code where the prolonged pressure takes you to the "hour menu" where with the single click you go on with the hours then you hold down for a long time and you go to the menu of minutes then you go back to the original operation. 

But in my code there are too many variables to intercept the prolonged and single pressures that don't work well and if I try to add more code to fix I don't have any more space in the micro. 😂😮‍💨

**Comment by techn0man1ac** [comment]
@edoxxx  I added a time setting (minutes) if you press and hold the button for more than 10 seconds, then the time will be added by 5 minutes per display cycle as long as the button is held.

**Comment by techn0man1ac** [comment]
https://www.youtube.com/shorts/7TG0KjUsHnk

**Comment by techn0man1ac** [comment]
https://www.youtube.com/shorts/7TG0KjUsHnk

**Comment by edoxxx** [comment]
This is really amazing. 
Now I think it's a really complete project.
Thank you very much!!

**Comment by techn0man1ac** [comment]
Thank you @edoxxx 

New feature and new bugs 🐞 🙂

It's just beginning, so a lot of work ahead 🚀
